# netlify.toml

[build]
  # Solo build: la exportación está gestionada por output: 'export' en next.config.js
  command = "npm run build"
  # Carpeta resultante con tu sitio estático
  publish = "out"

[dev]
  # Levanta tu servidor de desarrollo local
  command = "npm run dev"
  # Puerto por defecto de Next.js
  port    = 3000
  # Carpeta estática que Netlify Dev servirá
  publish = "out"
